Bg/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/',include("posts.urls")),
      path('api/',include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.contrib import admin
from posts import views
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from posts.views import profile_Update,User_edit_View,update_password

urlpatterns = [
    path('admin/', admin.site.urls),
    path("register/",views.register_view.as_view(),name="register"),
    path("login/",views.sign_view.as_view(),name="login"),
    path('logout/',views.sign_out.as_view(),name="logout"),
    path("blog/",views.blog_creation.as_view(),name="blog_create"),
    path("home/",views.blog_list.as_view(),name="blog_list"),
    path('profileupdate/', profile_Update.as_view(), name='profile_update'),
    path('yourprofilr/', views.profile_view.as_view(), name='profile_view'),
    path('blogdetail/<int:pk>', views.blog_single.as_view(), name='blog_view'),
    path('blogdelete/<int:pk>',views.blog_delete.as_view(), name='blog_delete'),
    path('blogupdate/<int:pk>',views.blog_update.as_view(), name='blog_update'),
    path('updateprofile/', User_edit_View.as_view(), name='profilechange'),
    path('updateps/', update_password, name='update_password'),
    path('search/', views.search_blogs, name='search_blogs'),
    # path('profileview/',profileview.as_view(), name='profile_create')
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from taggit.managers import TaggableManager

# Create your models here.


class profile(models.Model)  :
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='profile_pics', null=True,blank=True, default='profile_pics/r.jpeg')

    def __str__(self):
        return self.user.username 


class Blog(models.Model):   
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = RichTextField()  
    tags = TaggableManager(blank=True)  
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

posts/forms.py
from django import forms
from django.contrib.auth.models import User
from posts.models import profile
from posts.models import Blog
from django.contrib.auth.forms import UserChangeForm


class registerform(forms.ModelForm):
    class Meta:
        model=User
        fields=['username','password','email']


class signform(forms.Form):
   username=forms.CharField()
   password=forms.CharField()  

class profileForm(forms.ModelForm):
    class Meta:
        model=profile
        fields=['photo','user'] 
        widgets = {
            'photo': forms.FileInput(),  
        } 



class Blogform(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'content', 'tags']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'tags': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Comma separated tags'}),
        }    





class profileedit(UserChangeForm):
    class Meta:
        model = User
        fields = ['username', 'email']

class passwordchange(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput, label='Old Password')
    new_password = forms.CharField(widget=forms.PasswordInput, label='New Password')
    confirm_password = forms.CharField(widget=forms.PasswordInput, label='Confirm New Password')

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get('new_password')
        confirm_password = cleaned_data.get('confirm_password')

        if new_password != confirm_password:
            raise forms.ValidationError("The two password fields must match.")

posts/views.py
from django.shortcuts import render,redirect
from posts.forms import registerform,signform,Blogform,profileForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.utils.decorators import method_decorator
from posts.models import Blog,profile
from django.views.generic import View
from django.views.generic.edit import CreateView,UpdateView
from django.urls import reverse_lazy
from django.http import HttpResponseNotFound
from django.contrib import messages
from posts.forms import profileedit, passwordchange
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash



# Create your views here.

def signin_required(fn):
    def wrapper(request,*args,**store):
        if not request.user.is_authenticated:
            return redirect("login")
        else:
            return fn(request,*args,**store)
    return wrapper

def mylogin(fn):
    def wrapper(request,*args,**store):
        id=store.get("pk")
        obj=Blog.objects.get(id=id)
        if obj.author !=request.user:
            return redirect("login")
        else:
            return fn(request,*args,**store)
    return wrapper 




class register_view(View):
    def get(self,request,*args,**store):
        data=registerform()
        return render(request,"registration.html",{"data":data})
    
    def post(self,request,*args,**store):
         data=registerform(request.POST)
         if data.is_valid():
             print(data.cleaned_data)
             User.objects.create_user(**data.cleaned_data) 
             return redirect("login")
         else: 
             print() 
         data=registerform()
         return render(request,"registration.html",{"reg":data})
      
class sign_view(View):
    def get(self,request,*args,**store):
     data=signform()
     return render(request,"sign.html",{"sign":data})
    
    def post(self,request,*args,**store):
        data=signform(request.POST)
        if data.is_valid():
            print(data.cleaned_data)
            u_name=data.cleaned_data.get("username")
            pasw=data.cleaned_data.get("password")

            user_obj=authenticate(request,username=u_name,password=pasw)
            if user_obj:
               login(request,user_obj)
              
               return redirect("blog_list")
               
            else:
                print("user id not valid")  
                messages.error(request, "User ID not valid") 
            return redirect("login")  
        

class sign_out(View):
    def get(self,request,*args,**store):
        logout(request)
        return redirect("login")
    


#profile


# @method_decorator(signin_required,name='dispatch')        
# class profileview(CreateView):
#     model = profile
#     form_class = profileForm
#     template_name = 'registration.html'  
#     success_url = reverse_lazy('profile_create')  

#     def form_valid(self, form):
#         form.instance.name = self.request.user  
#         return super().form_valid(form)  
#     def get_queryset(self):
        
#         return profile.objects.filter(user=self.request.user)
  
      
@method_decorator(signin_required,name='dispatch')           
class profile_Update(UpdateView):
    model = profile
    form_class = profileForm      
    template_name = 'profile_update.html'
    success_url = reverse_lazy('profile_view')
    def get_object(self, queryset=None):
        return profile.objects.get(user=self.request.user) 


class profile_view(View):
   
      def get(self,request,*args,**kwargs):
          qs=profile.objects.get(user=request.user)
          return render(request, "profile_view.html", {"profile": qs})
      
#user  edit

class User_edit_View(UpdateView):
    model = User
    form_class =  profileedit
    template_name = 'user_update.html'
    success_url = reverse_lazy('profile_view')  

    def get_object(self, queryset=None):
        return self.request.user

@login_required
def update_password(request):
    if request.method == 'POST':
        password_form =  passwordchange(request.POST)
        if password_form.is_valid():
            user = request.user
            if user.check_password(password_form.cleaned_data['old_password']):
                user.set_password(password_form.cleaned_data['new_password'])
                user.save()
                update_session_auth_hash(request, user)  
                messages.success(request, 'Your password has been updated successfully.')
                return redirect('login') 
            else:
                messages.error(request, 'Old password is incorrect.')
    else:
        password_form =  passwordchange()

    context = {
        'password_form': password_form,
    }
    return render(request, 'update_password.html', context)


    

#blog
      
@method_decorator(signin_required,name='dispatch')   
class blog_creation(View):
     def get(self,request,*args,**kwargs):
        data=Blogform()
        return render(request,"blog_creation.html",{"blog":data})
     

     def post(self,request,*args,**kwargs):
          data=Blogform(request.POST)
          if data.is_valid():
               print(data.cleaned_data)
               data = data.save(commit=False)
               data.author = request.user
               data.save()
               return redirect('blog_list')  
          return render(request, "blog_creation.html", {"blog": data})
     


      
@method_decorator(signin_required,name='dispatch')   
class blog_list(View):
   
      def get(self,request,*args,**kwargs):
          
          data=Blog.objects.filter(author=request.user)
          prod=profile.objects.get(user=request.user)
          return render(request, "home.html", {"blog_data": data,"profile": prod})



    
@method_decorator(mylogin,name='dispatch') 
class blog_single(View):
   
      def get(self,request,*args,**kwargs):
          id=kwargs.get("pk")
          data=Blog.objects.filter(id=id)
          return render(request, "blog_single.html", {"data": data,})    
      

@method_decorator(mylogin,name='dispatch') 
class blog_delete(View):
    def get(self,request,*args,**store):
        id=store.get("pk")
        Blog.objects.filter(id=id).delete()        
        return redirect("blog_list") 

@method_decorator(mylogin,name='dispatch') 
class blog_update(View):

    def get(self, request, *args, **store):
        id = store.get("pk")  
        blog = Blog.objects.filter(id=id).first()  
        
        if blog is None:
            return HttpResponseNotFound("Blog not found") 

        data = Blogform(instance=blog)  
        return render(request, "blog_update.html", {"data": data})

    def post(self, request, *args, **store):
        id = store.get("pk") 
        blog = Blog.objects.filter(id=id).first()  
        
        if blog is None:
            return HttpResponseNotFound("Blog not found")  

        data = Blogform(request.POST, instance=blog)  
        if data.is_valid():
            data.save()  
            return redirect('blog_list') 
        
        
        return render(request,"blog_update.html", {"data": data})
    

def search_blogs(request):
    query = request.GET.get('q')  
    results = []

    if query:
        if query.isdigit():
              results = Blog.objects.filter(id=query)
        else:          
            results = Blog.objects.filter(title__icontains=query)
        return render(request, 'blog_single.html', {'results': results, 'query': query})

posts/templates/base.html
</body>
</html>
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Blog</title>

    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    
</head>
<body class="bg-gray-100 font-sans flex flex-col min-h-screen">

    <nav class="bg-gray-800 p-4">
        <div class="container mx-auto flex justify-between items-center">
            <a class="text-white text-lg font-bold" href="{% url 'blog_list' %}">MyBlogs</a>
            <div class="flex items-center space-x-4">
                <a href="{% url 'blog_create' %}" class="border border-yellow-400 text-yellow-400 px-4 py-2 rounded hover:bg-yellow-400 hover:text-black transition">Create a New Blog</a>

                <form class="flex space-x-2" role="search" action="{% url 'search_blogs' %}" method="get" onsubmit="return validateSearch()">
                    <input class="form-input px-4 py-2 border border-gray-300 rounded" type="search" name="q" placeholder="Search by ID or Title" aria-label="Search">
                    <button class="border border-yellow-400 text-yellow-400 px-4 py-2 rounded hover:bg-yellow-400 hover:text-black transition transform active:scale-95" type="submit">Search</button>
                </form>
                

                <div class="relative">
                    <button class="flex items-center text-white focus:outline-none" id="profileDropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-user mr-2"></i> Profile
                        <i class="fas fa-chevron-down"></i>
                    </button>
                    <div class="absolute right-0 mt-2 w-48 bg-gray-800 text-white rounded shadow-lg hidden transition-opacity duration-200 ease-in-out" id="dropdownMenu">
                        <a class="block px-4 py-2 hover:bg-yellow-400" href="{% url 'profile_view' %}">View Profile</a>
                        <hr class="border-gray-700">
                        <a class="block px-4 py-2 hover:bg-yellow-400" href="{% url 'logout' %}">Logout</a>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    
    <div class="flex-grow">
        {% block body %}
        {% endblock %}
    </div>

    
    <footer class="bg-gray-800 text-white py-6 mt-10">
        <div class="container mx-auto text-center">
            <div class="flex justify-center space-x-6 mb-4">
                <a href="#" class="text-yellow-400 hover:text-white transition"><i class="fab fa-facebook-f"></i></a>
                <a href="#" class="text-yellow-400 hover:text-white transition"><i class="fab fa-twitter"></i></a>
                <a href="#" class="text-yellow-400 hover:text-white transition"><i class="fab fa-instagram"></i></a>
                <a href="#" class="text-yellow-400 hover:text-white transition"><i class="fab fa-youtube"></i></a>
            </div>
            <p class="text-gray-400 text-sm">&copy; 2024 MyBlogs. All rights reserved.</p>
            <nav class="flex justify-center space-x-4 mt-4">
                <a href="{% url 'blog_list' %}" class="text-gray-400 hover:text-yellow-400 transition">Home</a>
                <a href="{% url 'profile_view' %}" class="text-gray-400 hover:text-yellow-400 transition">Profile</a>
                
            </nav>
        </div>
    </footer>

    <script>
        document.getElementById('profileDropdown').addEventListener('click', function() {
            const dropdownMenu = document.getElementById('dropdownMenu');
            dropdownMenu.classList.toggle('hidden');

            if (!dropdownMenu.classList.contains('hidden')) {
                dropdownMenu.classList.remove('hidden');
                dropdownMenu.classList.add('opacity-0', 'scale-95');
                setTimeout(() => {
                    dropdownMenu.classList.remove('opacity-0', 'scale-95');
                    dropdownMenu.classList.add('opacity-100', 'scale-100');
                }, 10);
            } else {
                dropdownMenu.classList.add('opacity-0', 'scale-95');
                setTimeout(() => {
                    dropdownMenu.classList.add('hidden');
                    dropdownMenu.classList.remove('opacity-100', 'scale-100');
                }, 200);
            }
        });

        
        window.addEventListener('click', function(event) {
            const dropdownMenu = document.getElementById('dropdownMenu');
            if (!event.target.closest('#profileDropdown')) {
                if (!dropdownMenu.classList.contains('hidden')) {
                    dropdownMenu.classList.add('opacity-0', 'scale-95');
                    setTimeout(() => {
                        dropdownMenu.classList.add('hidden');
                        dropdownMenu.classList.remove('opacity-100', 'scale-100');
                    }, 200);
                }
            }
        });

        
        function validateSearch() {
            const searchInput = document.querySelector('input[type="search"]');
            if (searchInput.value.trim() === '') {
                alert("Please enter a search term.");
                return false; 
            }
            return true; 
        }
    </script>

</body>
</html>

posts/templates/blog_creation.html
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Blog Post</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <style>
        .input-focus {
            transition: transform 0.2s ease;
        }
    </style>
</head>
<body class="bg-gray-100">
    <div class="container mx-auto my-10 max-w-xl bg-white p-8 rounded-lg shadow-md">
        <h2 class="text-2xl font-bold text-center text-gray-800 mb-6">Create Blog Post</h2>
        <form method="POST" onsubmit="return validateForm()">
            {% csrf_token %}
            <div class="mb-4">
                <label for="id_title" class="block text-sm font-semibold text-gray-700 mb-2">Title</label>
                {{ blog.title.errors }}
                <input type="text" name="title" id="id_title" placeholder="Enter your blog title" 
                    class="w-full border border-gray-300 rounded-lg p-3 focus:outline-none focus:ring-2 focus:ring-green-500 input-focus">
            </div>
            <div class="mb-4">
                <label for="id_content" class="block text-sm font-semibold text-gray-700 mb-2">Content</label>
                {{ blog.content.errors }}
                <textarea name="content" id="id_content" rows="6" placeholder="Write your blog content here..." 
                    class="w-full border border-gray-300 rounded-lg p-3 focus:outline-none focus:ring-2 focus:ring-green-500 input-focus"></textarea>
            </div>
            <div class="mb-4">
                <label for="id_tags" class="block text-sm font-semibold text-gray-700 mb-2">Tags</label>
                {{ blog.tags.errors }}
                <input type="text" name="tags" id="id_tags" placeholder="Enter tags separated by commas" 
                    class="w-full border border-gray-300 rounded-lg p-3 focus:outline-none focus:ring-2 focus:ring-green-500 input-focus">
            </div>
            <button type="submit" id="submitButton" class="w-full bg-green-500 text-white py-2 rounded hover:bg-green-600 transition transform active:scale-95">Submit</button>
            <a href="{% url 'blog_list' %}" id="cancelButton" class="w-full block text-center mt-3 bg-red-500 text-white py-2 rounded hover:bg-red-600 transition transform active:scale-95">Cancel</a>
        </form>
    </div>

    <script>
        
        document.querySelectorAll('.input-focus').forEach(input => {
            input.addEventListener('focus', () => {
                input.classList.add('scale-105'); 
            });
            input.addEventListener('blur', () => {
                input.classList.remove('scale-105'); 
            });
        });

        
        function validateForm() {
            const title = document.getElementById('id_title').value.trim();
            const content = document.getElementById('id_content').value.trim();
            const tags = document.getElementById('id_tags').value.trim();

            if (!title || !content) {
                alert("Title and content are required!");
                return false; 
            }
            return true;
        }

        
        const buttons = document.querySelectorAll('button, a');
        buttons.forEach(button => {
            button.addEventListener('mousedown', () => {
                button.classList.add('active:scale-95');
            });
            button.addEventListener('mouseup', () => {
                button.classList.remove('active:scale-95');
            });
        });
    </script>
</body>
</html>

posts/templates/blog_single.html
{% extends 'base.html' %}



{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ blog_post.title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #f8fafc; 
        }
    </style>
</head>
<body class="opacity-0 transition-opacity duration-500" id="blogBody">

    {% if query %}
    <div class="max-w-lg mx-auto p-4 bg-white rounded-lg shadow-md mt-10">
        <h2 class="text-xl font-bold mb-4">Search Results for "{{ query }}"</h2>
        {% if results %}
            <ul class="space-y-4">
                {% for blog in results %}
                    <li class="border-b border-gray-200 pb-2">
                        <h3 class="text-lg font-semibold">
                            <a href="{% url 'blog_view' blog.id %}">{{ blog.title }}</a>
                        </h3>
                        <p>{{ blog.summary }}</p>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No results found.</p>
        {% endif %}
    </div>
    {% endif %}

    
    {% for i in data %}
        <div class="max-w-lg mx-auto p-4 bg-white rounded-lg shadow-md mt-10 opacity-0 transition-opacity duration-500 transform scale-95 blog-post">
            <h1 class="text-3xl font-bold mb-4">{{ i.title }}</h1>
            <div class="text-lg leading-8 text-gray-600">
                <p>{{ i.content }}</p>
                <p class="text-sm text-gray-500 mb-4">Created at: {{ i.created_at }}</p>
                <div class="flex space-x-2">
                    <a href="{% url 'blog_delete' i.id %}" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded-lg transition-transform transform hover:scale-105">Delete</a>
                    <a href="{% url 'blog_update' i.id %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-lg transition-transform transform hover:scale-105">Update</a>
                </div>
            </div>
        </div>
    {% endfor %}

    <script>
        document.addEventListener("DOMContentLoaded", function() {
            const blogBody = document.getElementById('blogBody');
            const blogPosts = document.querySelectorAll('.blog-post');

            
            blogBody.classList.remove('opacity-0');
            blogBody.classList.add('opacity-100');

        
            blogPosts.forEach((post, index) => {
                setTimeout(() => {
                    post.classList.remove('opacity-0', 'scale-95');
                    post.classList.add('opacity-100', 'scale-100');
                }, index * 150); 
            });
        });

        function validateSearch() {
            const searchInput = document.querySelector('input[type="search"]');
            if (searchInput.value.trim() === '') {
                alert("Please enter a search term.");
                return false; 
            }
            return true; 
        }
    </script>

</body>
</html>

{% endblock %}

posts/templates/blog_update.html
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Blog Post</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100">
    <div class="container mx-auto my-10 max-w-xl bg-white p-8 rounded-lg shadow-md transform transition-all duration-500 scale-100 hover:scale-105">
        <h2 class="text-2xl font-bold text-center text-gray-800 mb-6">Update Blog</h2>
        <form method="POST">
            {% csrf_token %}
            <div class="mb-4">
                {{ data.title.errors }}
                <label for="id_title" class="block text-sm font-semibold text-gray-700 mb-2">Title</label>
                <input type="text" name="title" id="id_title" value="{{ data.title.value }}" 
                    class="w-full border border-gray-300 rounded-lg p-3 focus:outline-none focus:ring-2 focus:ring-blue-500 transition-transform duration-300" 
                    placeholder="Enter blog title">
            </div>
            <div class="mb-4">
                {{ data.content.errors }}
                <label for="id_content" class="block text-sm font-semibold text-gray-700 mb-2">Content</label>
                <textarea name="content" id="id_content" rows="6" 
                    class="w-full border border-gray-300 rounded-lg p-3 focus:outline-none focus:ring-2 focus:ring-blue-500 transition-transform duration-300" 
                    placeholder="Write your blog content here...">{{ data.content.value }}</textarea>
            </div>
            <button type="submit" class="w-full bg-blue-500 text-white py-2 rounded hover:bg-blue-600 transition transform active:scale-95 duration-300">Submit</button>
            <a href="{% url 'blog_list' %}" class="w-full block text-center mt-3 bg-red-500 text-white py-2 rounded hover:bg-red-600 transition transform active:scale-95 duration-300">Cancel</a>
        </form>
    </div>
</body>
</html>

posts/templates/home.html
{% extends 'base.html' %}

{% block body %}

<div class="container mx-auto my-5">
    <div class="flex justify-between items-center mb-4">
        <h1 class="text-2xl font-bold">Welcome, {{ request.user }}</h1>
    </div>

    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        {% for i in blog_data %}
        <div class="bg-white shadow-md rounded-lg overflow-hidden transform transition-transform duration-500 scale-100 opacity-0 enter-animation">
            <div class="p-4">
                <h5 class="text-lg font-semibold">{{ i.title }}</h5>
                <p class="text-gray-700 mb-2">{{ i.content|truncatewords:30 }}</p>
                <p class="text-gray-500 text-sm">Created at: {{ i.created_at }}</p>
                <a href="{% url 'blog_view' i.id %}" class="mt-4 inline-block bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 transition">Read More</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        const cards = document.querySelectorAll('.enter-animation');

        const options = {
            root: null,
            rootMargin: '0px',
            threshold: 0.1
        };

        const observer = new IntersectionObserver((entries, observer) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    entry.target.classList.remove('opacity-0');
                    entry.target.classList.add('opacity-100', 'scale-105');
                    observer.unobserve(entry.target); 
                }
            });
        }, options);

        cards.forEach(card => {
            observer.observe(card);
        });
    });
</script>

{% endblock %}

posts/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Upload Profile Photo</title>
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100">

  {% block body %}

  {% endblock %}

  <div class="container mx-auto my-10 max-w-md bg-white p-6 rounded-lg shadow-lg opacity-0 transition-transform transform scale-90 enter-animation">
      <h2 class="text-2xl font-bold text-center mb-4">Upload Profile Photo</h2>
      <form method="post" enctype="multipart/form-data" class="space-y-4">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="w-full bg-blue-500 text-white py-2 rounded hover:bg-blue-600 transition transform active:scale-95">Submit</button>
      </form>
  </div>

  <script>
      document.addEventListener("DOMContentLoaded", function() {
          const formContainer = document.querySelector('.enter-animation');

          const options = {
              root: null,
              rootMargin: '0px',
              threshold: 0.1
          };

          const observer = new IntersectionObserver((entries, observer) => {
              entries.forEach(entry => {
                  if (entry.isIntersecting) {
                      entry.target.classList.remove('opacity-0', 'scale-90');
                      entry.target.classList.add('opacity-100', 'scale-100');
                      observer.unobserve(entry.target); // Stop observing after animation
                  }
              });
          }, options);

          observer.observe(formContainer);
      });
  </script>

</body>
</html>

posts/templates/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Registration Form</title>
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
  <form method="post" enctype="multipart/form-data" class="bg-white p-6 border border-gray-300 rounded-lg shadow-md w-96 mx-auto mt-40">
    {% csrf_token %}
    <h1 class="text-lg font-bold mb-4">Registration Form</h1>
    <p class="mb-10">Please fill in this form to create an account.</p>
    <hr class="mb-10">

    <label for="username" class="block font-bold mb-2"><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="username" required class="w-full p-2 mb-4 border border-gray-300 rounded-lg">

    <label for="password" class="block font-bold mb-2"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="password" required class="w-full p-2 mb-4 border border-gray-300 rounded-lg">

    <label for="email" class="block font-bold mb-2"><b>Email</b></label>
    <input type="email" placeholder="Enter Email" name="email" required class="w-full p-2 mb-4 border border-gray-300 rounded-lg">

    

    <button type="submit" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-lg">Register</button>

    <hr class="mb-10">
    <p class="mb-4">By creating an account you agree to our <a href="#" class="text-dodgerblue">Terms & Privacy</a>.</p>
    <p class="mt-4">Already have an account? <button class="bg-white hover:bg-gray-100 text-gray-800 font-bold py-2 px-4 rounded-lg" onclick="window.location.href='{% url 'login' %}'">Login</button></p>
  </form>
</body>
</html>